# Generated by Django 4.0.3 on 2022-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_banner_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, default='banners/no-banner-available.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movies/poster-not-available.jpg', upload_to=''),
        ),
    ]
