# Generated by Django 4.0.3 on 2022-05-08 12:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_person_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('action', 'ACTION'), ('adventure', 'ADVENTURE'), ('animated', 'ANIMATED'), ('comedy', 'COMEDY'), ('crime', 'CRIME'), ('drama', 'DRAMA'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('historical', 'HISTORICAL'), ('romance', 'ROMANCE'), ('western', 'WESTERN'), ('science-fiction', 'SCIENCE FICTION')], max_length=102),
        ),
    ]
