# Generated by Django 4.0.3 on 2022-05-08 12:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='persons/person-no-available.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('action', 'ACTION'), ('adventure', 'ADVENTURE'), ('animated', 'ANIMATED'), ('comedy', 'COMEDY'), ('crime', 'CRIME'), ('drama', 'DRAMA'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('historical', 'HISTORICAL'), ('romance', 'ROMANCE'), ('western', 'WESTERN'), ('science-fiction', 'SCIENCE FICTION')], max_length=102, null=True),
        ),
    ]
