# Generated by Django 4.0.3 on 2022-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_person_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecast',
            name='played_as',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
