# Generated by Django 4.0.3 on 2022-06-29 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0011_moviecast_played_as'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_comments', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, default='../media/banners/no-banner-available.jpg', null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, choices=[('action', 'ACTION'), ('adventure', 'ADVENTURE'), ('animated', 'ANIMATED'), ('comedy', 'COMEDY'), ('crime', 'CRIME'), ('drama', 'DRAMA'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('historical', 'HISTORICAL'), ('romance', 'ROMANCE'), ('western', 'WESTERN'), ('science-fiction', 'SCIENCE FICTION')], max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='../media/movies/poster-not-available.jpg', null=True, upload_to='../media/movies/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_category',
            field=models.CharField(blank=True, choices=[('action', 'ACTION'), ('adventure', 'ADVENTURE'), ('animated', 'ANIMATED'), ('comedy', 'COMEDY'), ('crime', 'CRIME'), ('drama', 'DRAMA'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('historical', 'HISTORICAL'), ('romance', 'ROMANCE'), ('western', 'WESTERN'), ('science-fiction', 'SCIENCE FICTION')], max_length=128, null=True),
        ),
    ]
