# Generated by Django 4.0.3 on 2022-07-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_moviecomment_movie_alter_moviecomment_sender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blocklist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blocklist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='blocklist',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='history',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='BlockList',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
