# Generated by Django 4.0.3 on 2022-07-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_blocklist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, default='../media/banners/no-banner-available.jpg', null=True, upload_to='../media/banners/'),
        ),
    ]
